spring :
  application :
    name : protin_cal

  datasource:
    url: jdbc:mysql://localhost:3307/protin
    username: root
    password: tagtag1010
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
